site_name: National Volcano Model Documentation

theme:
  name: material
  logo: assets/NVM_logo_only_white.png
  favicon: assets/NVM_logo_only_white.png

  palette:
    - scheme: default
      primary: custom
      accent: custom

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Overview: index.md
  - Model:
      - Hazard: hazard.md
      - Vulnerability: vulnerability.md
      - Risk: risk.md
  - Outputs: outputs.md
  - Usage: usage.md